# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links: 
  Github: https://github.com/jianglin-wu
  YApi 工具: http://132.232.51.241:3000
  图床工具: http://image.sv-1.psyduck.top

# Miscellaneous
google_analytics: UA-119970863-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
# duoshuo_shortname: reqianduan

# Baidu share
# baidushare: false