# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  Github: https://github.com/jianglin-wu
  # YApi: https://yapi.sv-0.hahhub.com
  # Chevereto: https://image.hahhub.com

gitalk:
  enable: true
  githubID: jianglin-wu
  repo: jianglin-wu.github.io
  ClientID: abbd1bd4898140bf47c3
  ClientSecret: 6382e9ab7130fcd3756b7d15679948d65184b148
  adminUser: jianglin-wu
  distractionFreeMode: false

# Miscellaneous
google_analytics: UA-119970863-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
# duoshuo_shortname: reqianduan

# Baidu share
# baidushare: false